// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localUsers,
    argoConnections,
    studentProfiles,
    subjects,
    sourceRecords,
    homeworkItems,
    deadlines,
    completions,
    reminders,
    syncStates,
    homeworkIdentityMappings,
    profilesByConnectionYear,
    subjectsByProfileYear,
    sourceRecordsByProfileDay,
    homeworkByProfileState,
    homeworkByProfileSubject,
    deadlinesBySourceDue,
    deadlinesByPersonalDue,
  ];
  late final Shape0 localUsers = Shape0(
    source: i0.VersionedTable(
      entityName: 'local_users',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 argoConnections = Shape1(
    source: i0.VersionedTable(
      entityName: 'argo_connections',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(user_id, school_ministry_code)',
      ],
      columns: [
        _column_0,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 studentProfiles = Shape2(
    source: i0.VersionedTable(
      entityName: 'student_profiles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(connection_id, source_profile_id)',
      ],
      columns: [
        _column_0,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 subjects = Shape3(
    source: i0.VersionedTable(
      entityName: 'subjects',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(profile_id, academic_year, name)',
      ],
      columns: [
        _column_0,
        _column_18,
        _column_16,
        _column_19,
        _column_20,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 sourceRecords = Shape4(
    source: i0.VersionedTable(
      entityName: 'source_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(profile_id, source_primary_key)',
      ],
      columns: [
        _column_0,
        _column_18,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 homeworkItems = Shape5(
    source: i0.VersionedTable(
      entityName: 'homework_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_18,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_13,
        _column_37,
        _column_38,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 deadlines = Shape6(
    source: i0.VersionedTable(
      entityName: 'deadlines',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 completions = Shape7(
    source: i0.VersionedTable(
      entityName: 'completions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(user_id, homework_id)'],
      columns: [
        _column_8,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 reminders = Shape8(
    source: i0.VersionedTable(
      entityName: 'reminders',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_8, _column_46, _column_50, _column_51],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 syncStates = Shape9(
    source: i0.VersionedTable(
      entityName: 'sync_states',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(profile_id)'],
      columns: [
        _column_18,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 homeworkIdentityMappings = Shape10(
    source: i0.VersionedTable(
      entityName: 'homework_identity_mappings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(profile_id, source_record_id, nested_identity)',
      ],
      columns: [
        _column_18,
        _column_58,
        _column_28,
        _column_59,
        _column_35,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index profilesByConnectionYear = i1.Index(
    'profiles_by_connection_year',
    'CREATE INDEX profiles_by_connection_year ON student_profiles (connection_id, academic_year)',
  );
  final i1.Index subjectsByProfileYear = i1.Index(
    'subjects_by_profile_year',
    'CREATE INDEX subjects_by_profile_year ON subjects (profile_id, academic_year)',
  );
  final i1.Index sourceRecordsByProfileDay = i1.Index(
    'source_records_by_profile_day',
    'CREATE INDEX source_records_by_profile_day ON source_records (profile_id, record_day)',
  );
  final i1.Index homeworkByProfileState = i1.Index(
    'homework_by_profile_state',
    'CREATE INDEX homework_by_profile_state ON homework_items (profile_id, source_state)',
  );
  final i1.Index homeworkByProfileSubject = i1.Index(
    'homework_by_profile_subject',
    'CREATE INDEX homework_by_profile_subject ON homework_items (profile_id, subject_id)',
  );
  final i1.Index deadlinesBySourceDue = i1.Index(
    'deadlines_by_source_due',
    'CREATE INDEX deadlines_by_source_due ON deadlines (source_due_on)',
  );
  final i1.Index deadlinesByPersonalDue = i1.Index(
    'deadlines_by_personal_due',
    'CREATE INDEX deadlines_by_personal_due ON deadlines (personal_due_on)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get locale =>
      columnsByName['locale']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get theme =>
      columnsByName['theme']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get timeZone =>
      columnsByName['time_zone']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get preferencesJson =>
      columnsByName['preferences_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get privacyNoticeVersion =>
      columnsByName['privacy_notice_version']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ageBand =>
      columnsByName['age_band']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'locale',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'it\''),
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'theme',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'system\''),
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'time_zone',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'Europe/Rome\''),
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'preferences_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'{}\''),
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'privacy_notice_version',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'age_band',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<DateTime> _column_7(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get schoolMinistryCode =>
      columnsByName['school_ministry_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get role =>
      columnsByName['role']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get secretReference =>
      columnsByName['secret_reference']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sessionState =>
      columnsByName['session_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'user_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES local_users (id)',
      ),
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'school_ministry_code',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'role',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'family\''),
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'secret_reference',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'session_state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'active\''),
    );
i1.GeneratedColumn<DateTime> _column_13(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get connectionId =>
      columnsByName['connection_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceProfileId =>
      columnsByName['source_profile_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get academicYear =>
      columnsByName['academic_year']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get alias =>
      columnsByName['alias']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'connection_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES argo_connections (id)',
      ),
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_profile_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'academic_year',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'alias',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get profileId =>
      columnsByName['profile_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get academicYear =>
      columnsByName['academic_year']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceSubjectId =>
      columnsByName['source_subject_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get colorValue =>
      columnsByName['color_value']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'profile_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES student_profiles (id)',
      ),
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_subject_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'color_value',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get profileId =>
      columnsByName['profile_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourcePrimaryKey =>
      columnsByName['source_primary_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get revision =>
      columnsByName['revision']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get recordDay =>
      columnsByName['record_day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_primary_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'revision',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'active\''),
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'record_day',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get profileId =>
      columnsByName['profile_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceRecordId =>
      columnsByName['source_record_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get subjectId =>
      columnsByName['subject_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nestedIdentity =>
      columnsByName['nested_identity']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceItemId =>
      columnsByName['source_item_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get identityConfidence =>
      columnsByName['identity_confidence']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get origin =>
      columnsByName['origin']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get body =>
      columnsByName['body']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get personalNote =>
      columnsByName['personal_note']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get assignedOn =>
      columnsByName['assigned_on']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentRevision =>
      columnsByName['content_revision']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get firstSeenAt =>
      columnsByName['first_seen_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get sourceState =>
      columnsByName['source_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get requiresIdentityReview =>
      columnsByName['requires_identity_review']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_record_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES source_records (id)',
      ),
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'subject_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES subjects (id)',
      ),
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'nested_identity',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_item_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'identity_confidence',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'origin',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'body',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'personal_note',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'assigned_on',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'content_revision',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<DateTime> _column_36(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'first_seen_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'active\''),
    );
i1.GeneratedColumn<bool> _column_38(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'requires_identity_review',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("requires_identity_review" IN (0, 1))',
      ),
      defaultValue: const CustomExpression('0'),
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get homeworkId =>
      columnsByName['homework_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceDueOn =>
      columnsByName['source_due_on']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get personalDueOn =>
      columnsByName['personal_due_on']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceTime =>
      columnsByName['source_time']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get schoolTimeZone =>
      columnsByName['school_time_zone']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get precision =>
      columnsByName['precision']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get provenance =>
      columnsByName['provenance']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'homework_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'UNIQUE REFERENCES homework_items (id)',
      ),
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_due_on',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'personal_due_on',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_time',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'school_time_zone',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'Europe/Rome\''),
    );
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'precision',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'date\''),
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'provenance',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'argo\''),
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get homeworkId =>
      columnsByName['homework_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isDone =>
      columnsByName['is_done']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<DateTime> get doneAt =>
      columnsByName['done_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get completedRevision =>
      columnsByName['completed_revision']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'homework_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES homework_items (id)',
      ),
    );
i1.GeneratedColumn<bool> _column_47(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'is_done',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("is_done" IN (0, 1))',
      ),
      defaultValue: const CustomExpression('0'),
    );
i1.GeneratedColumn<DateTime> _column_48(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'done_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'completed_revision',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get homeworkId =>
      columnsByName['homework_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get remindAt =>
      columnsByName['remind_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<DateTime> _column_50(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'remind_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'scheduled\''),
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get profileId =>
      columnsByName['profile_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get adapterVersion =>
      columnsByName['adapter_version']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cursor =>
      columnsByName['cursor']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get lastAttemptAt =>
      columnsByName['last_attempt_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get lastSuccessAt =>
      columnsByName['last_success_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get coverageStart =>
      columnsByName['coverage_start']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get errorCode =>
      columnsByName['error_code']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'adapter_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cursor',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<DateTime> _column_54(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'last_attempt_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<DateTime> _column_55(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'last_success_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<DateTime> _column_56(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'coverage_start',
      aliasedName,
      true,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'error_code',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get profileId =>
      columnsByName['profile_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceRecordId =>
      columnsByName['source_record_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nestedIdentity =>
      columnsByName['nested_identity']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get homeworkId =>
      columnsByName['homework_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentRevision =>
      columnsByName['content_revision']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_58(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_record_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'homework_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
